### ISSUE TITLE
Error callback was already called

### ISSUE THREAD

**Issue by razerrazer** [samuel-p/cachet-monitor#1]
Trace: Error: Error: Callback was already called.
    at process.on (/var/www/monitor/bin/cachet-monitor/node_modules/libnmap/lib/libnmap.js:116:17)
    at process.emit (events.js:198:13)
    at process._fatalException (internal/bootstrap/node.js:497:27)
    at process.on (/var/www/monitor/bin/cachet-monitor/node_modules/libnmap/lib/libnmap.js:116:11)
    at process.emit (events.js:198:13)
    at process._fatalException (internal/bootstrap/node.js:497:27)

**Comment by samuel-p** [comment]
Thanks for reporting. Can you please give some more Information on what you were trying to do? 

Did you use the Docker image? What type did you try to monitor? `TCP`, `UDP`? Maybe you can also share your config too.

**Comment by razerrazer** [comment]
Hi,

I tried to add 4 new DNS servers with UDP/TCP port 53. I have tried them differently like change from TCP to UDP and the other way around.

This is not a docker image. this is a Centos 7 x86_64 latest.

Here is the configuration:

{
	"cron": "0 * * * * *",
	"api": "http://xxxxxxxx/api/v1",
	"token": "xxxxxxxxxxxxxxxxxx",
	"services": [
		{
			"id": 2,
			"type": "HTTP",
			"url": "https://www.google.se",
			"performanceTimeout": 1
		},
        	
                {
			"id": 3,
			"type": "TCP",
			"host": "mail.smartemail.se",
			"port": 465
		},
                
                {
                        "id": 4,
                        "type": "TCP",
                        "host": "mail.smartemail.se",
                        "port": 995 
                },
                
                {
                        "id": 5,
                        "type": "HTTP",
                        "url": "https://mail.smartemail.se",
                        "performanceTimeout": 1 
                },
                 
                {
                        "id": 6,
                        "type": "TCP",
                        "host": "mail.smartemail.se",
                        "port": 993 
                },
 
               {
                        "id": 16,
                        "type": "HTTP",
                        "url": "https://da101.admax.se:2222",
                        "performanceTimeout": 1
                },
 
                {
                        "id": 17,
                        "type": "HTTP",
                        "url": "https://da102.admax.se:2222",
                        "performanceTimeout": 1
                },

                {
                        "id": 20,
                        "type": "UDP",
                        "host": "ns1.worldcastdns.se",
                        "port": 53
                },

                {
                        "id": 21,
                        "type": "UDP",
                        "host": "ns2.worldcastdns.com",
                        "port": 53
                },
                
                {
                        "id": 22,
                        "type": "UDP",
                        "host": "ns3.worldcastdns.eu",
                        "port": 53
                },

                {
                        "id": 23,
                        "type": "UDP",
                        "host": "ns4.worldcastdns.us",
                        "port": 53
                }

	],
	"defaults": {
		"retry": 0,
		"waitUntilRetry": 5,
		"performanceTimeout": 2,
		"requestTimeout": 15,
		"offlineTimeUntilMajor": 600
	}
}

**Comment by samuel-p** [comment]
Ok, I think I got this: The Problem was that one of your hosts seems to block `nmap` requests. So I added the `-Pn` flag to the `nmap` call and it should work now. I just pushed an update. Can you please check with the new version and confirm that it works for you as well?
